## 1. Data Loading + Initial Exploration
### Load All Datasets

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
customers = pd.read_csv(r"C:\Users\heman\Downloads\Santhu\VSCode\LogicMojo-AI-ML-March26-SanthoshKumar\projects\ecommerce_project\files\python_project_aiml_logicmojo_dataset\customers.csv")

print(customers.head())
customers.info()
customers.describe()

                        customer_id                customer_unique_id  \
0  06b8999e2fba1a1fbc88172c00ba8bc7  861eff4711a542e4b93843c6dd7febb0
1  18955e83d337fd6b2def6b18a428ac77  290c77bc529b7ac935b93aa66c333dc3
2  4e7b3e00288586ebd08712fdd0374a03  060e732b5b29e8181a18229c7b0b2b5e
3  b2b6027bc5c5109e529d4dc6358b12c3  259dac757896d24d7702b9acbbff3f3c
4  4f2d8ab171c80ec8364f7c12e35b23ad  345ecd01c38d18a9036ed96c73b8d066

   customer_zip_code_prefix          customer_city customer_state
0                     14409                 franca             SP
1                      9790  sao bernardo do campo             SP
2                      1151              sao paulo             SP
3                      8775        mogi das cruzes             SP
4                     13056               campinas             SP
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  object
 1   customer_unique_id        99441 non-null  object
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  object
 4   customer_state            99441 non-null  object
dtypes: int64(1), object(4)
memory usage: 3.8+ MB

       customer_zip_code_prefix
count              99441.000000
mean               35137.474583
std                29797.938996
min                 1003.000000
25%                11347.000000
50%                24416.000000
75%                58900.000000
max                99990.000000

In [4]:
orders = pd.read_csv(r"C:\Users\heman\Downloads\Santhu\VSCode\LogicMojo-AI-ML-March26-SanthoshKumar\projects\ecommerce_project\files\python_project_aiml_logicmojo_dataset\orders.csv")
orders.head()
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  object
 4   order_approved_at              99281 non-null  object
 5   order_delivered_carrier_date   97658 non-null  object
 6   order_delivered_customer_date  96476 non-null  object
 7   order_estimated_delivery_date  99441 non-null  object
dtypes: object(8)
memory usage: 6.1+ MB

In [5]:
order_items = pd.read_csv(r"C:\Users\heman\Downloads\Santhu\VSCode\LogicMojo-AI-ML-March26-SanthoshKumar\projects\ecommerce_project\files\python_project_aiml_logicmojo_dataset\order_item.csv")
order_items.head()
order_items.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  object
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  object
 3   seller_id            112650 non-null  object
 4   shipping_limit_date  112650 non-null  object
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: float64(2), int64(1), object(4)
memory usage: 6.0+ MB

In [6]:
payments = pd.read_csv(r"C:\Users\heman\Downloads\Santhu\VSCode\LogicMojo-AI-ML-March26-SanthoshKumar\projects\ecommerce_project\files\python_project_aiml_logicmojo_dataset\payments.csv")
payments.head()
payments.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103886 entries, 0 to 103885
Data columns (total 5 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   order_id              103886 non-null  object
 1   payment_sequential    103886 non-null  int64
 2   payment_type          103886 non-null  object
 3   payment_installments  103886 non-null  int64
 4   payment_value         103886 non-null  float64
dtypes: float64(1), int64(2), object(2)
memory usage: 4.0+ MB

In [7]:
reviews = pd.read_csv(r"C:\Users\heman\Downloads\Santhu\VSCode\LogicMojo-AI-ML-March26-SanthoshKumar\projects\ecommerce_project\files\python_project_aiml_logicmojo_dataset\reviews.csv")
reviews.head()
reviews.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99224 entries, 0 to 99223
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   review_id                99224 non-null  object
 1   order_id                 99224 non-null  object
 2   review_score             99224 non-null  int64
 3   review_comment_title     11568 non-null  object
 4   review_comment_message   40977 non-null  object
 5   review_creation_date     99224 non-null  object
 6   review_answer_timestamp  99224 non-null  object
dtypes: int64(1), object(6)
memory usage: 5.3+ MB

In [8]:
products = pd.read_csv(r"C:\Users\heman\Downloads\Santhu\VSCode\LogicMojo-AI-ML-March26-SanthoshKumar\projects\ecommerce_project\files\python_project_aiml_logicmojo_dataset\products.csv")
products.head()
products.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_id                  32951 non-null  object
 1   product_category_name       32341 non-null  object
 2   product_name_lenght         32341 non-null  float64
 3   product_description_lenght  32341 non-null  float64
 4   product_photos_qty          32341 non-null  float64
 5   product_weight_g            32949 non-null  float64
 6   product_length_cm           32949 non-null  float64
 7   product_height_cm           32949 non-null  float64
 8   product_width_cm            32949 non-null  float64
dtypes: float64(7), object(2)
memory usage: 2.3+ MB

In [9]:
sellers = pd.read_csv(r"C:\Users\heman\Downloads\Santhu\VSCode\LogicMojo-AI-ML-March26-SanthoshKumar\projects\ecommerce_project\files\python_project_aiml_logicmojo_dataset\sellers.csv")
sellers.head()
sellers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3095 entries, 0 to 3094
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   seller_id               3095 non-null   object
 1   seller_zip_code_prefix  3095 non-null   int64
 2   seller_city             3095 non-null   object
 3   seller_state            3095 non-null   object
dtypes: int64(1), object(3)
memory usage: 96.8+ KB

In [10]:
category_translation = pd.read_csv(r"C:\Users\heman\Downloads\Santhu\VSCode\LogicMojo-AI-ML-March26-SanthoshKumar\projects\ecommerce_project\files\python_project_aiml_logicmojo_dataset\category_translation.csv" )
category_translation.head()
category_translation.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 71 entries, 0 to 70
Data columns (total 2 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   product_category_name          71 non-null     object
 1   product_category_name_english  71 non-null     object
dtypes: object(2)
memory usage: 1.2+ KB

In [11]:
location = pd.read_csv(r"C:\Users\heman\Downloads\Santhu\VSCode\LogicMojo-AI-ML-March26-SanthoshKumar\projects\ecommerce_project\files\python_project_aiml_logicmojo_dataset\location.csv")
location.head()
# location.info()

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,1037,-23.545621,-46.639292,sao paulo,SP
1,1046,-23.546081,-46.644820,sao paulo,SP
2,1046,-23.546129,-46.642951,sao paulo,SP
3,1041,-23.544392,-46.639499,sao paulo,SP
4,1035,-23.541578,-46.641607,sao paulo,SP

## 2. Data Cleaning and Preprocessing

### 2.1 - Handling Mssing Values

In [12]:
# ============================================================
# Handling Missing Values
# ============================================================
# Missing value analysis was performed on all datasets.
# Missing values were handled based on business context,
# data importance, and analytical relevance.
# Business-state null values were retained where appropriate,
# while metadata and numerical fields were imputed using
# suitable strategies.
# ============================================================



# ============================================================
# Customers Dataset
# ============================================================

customers.isna().sum()

# This dataset does not contain missing values.

customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

In [13]:
# ============================================================
# Orders Dataset
# ============================================================

orders.isna().sum()

# The orders dataset contains null values in the following columns:
# - order_approved_at
# - order_delivered_carrier_date
# - order_delivered_customer_date

# These null values were analyzed using order_status to understand
# whether they represent actual data quality issues or valid
# business scenarios.

# ============================================================
# Orders_approved_at Analysis
# ============================================================

# Check order status for missing approval dates
orders[orders['order_approved_at'].isnull()]['order_status'].value_counts()

# Replacing order_approved_at null values with order_purchase_timestamp for delivered orders
mask = (
    (orders['order_approved_at'].isna()) &
    (orders['order_status'] == 'delivered')
)

orders.loc[mask, 'order_approved_at'] = orders.loc[
    mask,
    'order_purchase_timestamp'
]

# print(orders[(orders['order_approved_at'].isna()) & (orders['order_status'] == 'delivered')].sum())


# ============================================================
# order_delivered_carrier_date Analysis
# ============================================================

# Check order statuses where carrier delivery date is missing
print(
    orders[
        orders['order_delivered_carrier_date'].isna()
    ]['order_status'].value_counts()
)

# -------------------------------------------------------------
# Observation:
#
# - For statuses like:
#     unavailable, canceled, processing, created, approved
#   missing carrier date is logically acceptable because
#   the order may not have reached shipping stage.
#
# - But for 'delivered' orders:
#   carrier delivery date SHOULD exist because an order
#   cannot be delivered to customer without first being
#   handed over to the carrier.
#
# - Therefore, delivered orders with missing
#   order_delivered_carrier_date are inconsistent records.
# -------------------------------------------------------------


# Display those inconsistent delivered rows
orders[
    (orders['order_delivered_carrier_date'].isna()) &
    (orders['order_status'] == 'delivered')
].head(50)


# -------------------------------------------------------------
# Create a mask for inconsistent rows:
#
# Condition:
#   1. carrier delivery date is missing
#   2. order status is delivered
#
# These rows violate normal business workflow.
# -------------------------------------------------------------
mask = (
    (orders['order_delivered_carrier_date'].isna()) &
    (orders['order_status'] == 'delivered')
)


# -------------------------------------------------------------
# Remove inconsistent rows from dataset
#
# '~mask' means:
#   keep all rows EXCEPT rows where mask=True
#
# Since only 2 rows are affected,
# dropping them is safer than imputing artificial values.
# -------------------------------------------------------------
orders = orders[~mask]




# ============================================================
# order_delivered_customer_date Analysis
# ============================================================

# Check order statuses where customer delivery date is missing
print(
    orders[
        orders['order_delivered_customer_date'].isna()
    ]['order_status'].value_counts()
)

# Display inconsistent delivered rows
orders[
    (orders['order_delivered_customer_date'].isna()) &
    (orders['order_status'] == 'delivered')
]

# Create mask for inconsistent rows
mask = (
    (orders['order_delivered_customer_date'].isna()) &
    (orders['order_status'] == 'delivered')
)

# Remove inconsistent rows
orders = orders[~mask]

order_status
unavailable    609
canceled       550
invoiced       314
processing     301
created          5
approved         2
delivered        2
Name: count, dtype: int64
order_status
shipped        1107
canceled        619
unavailable     609
invoiced        314
processing      301
delivered         7
created           5
approved          2
Name: count, dtype: int64

In [14]:
# ============================================================
# Order Items Dataset
# ============================================================

order_items.isna().sum()

# This dataset does not contain missing values.

order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64

In [17]:
# ============================================================
# Payments Dataset
# ============================================================

payments.isna().sum()

# This dataset does not contain missing values.

order_id                0
payment_sequential      0
payment_type            0
payment_installments    0
payment_value           0
dtype: int64

In [19]:
# Check missing values in reviews dataset
# print(reviews.isna().sum())

# Fill missing review titles with placeholder text
reviews['review_comment_title'] = reviews[
    'review_comment_title'
].fillna('No Title')

# Fill missing review messages with placeholder text
reviews['review_comment_message'] = reviews[
    'review_comment_message'
].fillna('No Comment')

# Verify missing values after handling
print(reviews.isna().sum())

review_id                  0
order_id                   0
review_score               0
review_comment_title       0
review_comment_message     0
review_creation_date       0
review_answer_timestamp    0
dtype: int64

In [20]:
# Check missing values in products dataset
print(products.isna().sum())

# ---------------------------------------------------------
# Product Dataset Missing Value Analysis
#
# Group 1:
# The following columns contain 610 missing values
# for the same rows:
#
# - product_category_name
# - product_name_lenght
# - product_description_lenght
# - product_photos_qty
#
# These columns represent important product metadata.
# Since major product information is missing,
# removing these rows is a better approach.
# ---------------------------------------------------------

# Display rows with missing product metadata
# print(products[products['product_category_name'].isna()].head(50))


# Remove rows with missing core product information
products = products.dropna(
    subset=[
        'product_category_name',
        'product_name_lenght',
        'product_description_lenght',
        'product_photos_qty'
    ]
)


# ---------------------------------------------------------
# Group 2:
# The following columns contain only 2 missing values:
#
# - product_weight_g
# - product_length_cm
# - product_height_cm
# - product_width_cm
#
# These columns represent physical product dimensions.
# Instead of removing rows, we fill missing values
# using median values.
# ---------------------------------------------------------

# Display rows with missing product dimensions
# print(products[products['product_weight_g'].isnull()].head(50))


# List of dimension columns
dimension_cols = [
    'product_weight_g',
    'product_length_cm',
    'product_height_cm',
    'product_width_cm'
]


# Fill missing dimension values using median
for col in dimension_cols:
    products[col] = products[col].fillna(
        products[col].median()
    )


# Verify missing values after handling
print(products.isna().sum())

product_id                    0
product_category_name         0
product_name_lenght           0
product_description_lenght    0
product_photos_qty            0
product_weight_g              0
product_length_cm             0
product_height_cm             0
product_width_cm              0
dtype: int64
product_id                    0
product_category_name         0
product_name_lenght           0
product_description_lenght    0
product_photos_qty            0
product_weight_g              0
product_length_cm             0
product_height_cm             0
product_width_cm              0
dtype: int64

### 2.2 - Handling duplicate values

In [16]:
customers.duplicated().sum()

orders.duplicated().sum()

print(order_items.duplicated().sum())

payments.duplicated().sum()

reviews.duplicated().sum()

products.duplicated().sum()

sellers.duplicated().sum()

category_translation.duplicated().sum()

location.duplicated().sum()

0

np.int64(261831)